#!/bin/bash
clear
apt update && apt upgrade -y
apt install socat cron zip unzip -y
apt install curl
apt install apache2
apt install php
apt install libapache2-mod-php
apt install mysql-server
mysql_secure_installation
mysql
UNINSTALL COMPONENT "file://component_validate_password";
exit
apt install phpmyadmin
mysql
INSTALL COMPONENT "file://component_validate_password";
mysql
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'DeviAconk+x666';

sudo snap install core; sudo snap refresh core
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
sudo certbot --apache
sudo certbot certonly --apache
sudo certbot renew --dry-run
clear

